version: "3.8"
services:
  gateway-mt:
    image: storjlabs/gateway-mt:dev
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1.5'
          memory: 1024M
        reservations:
          memory: 512M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    # volumes:
    #   - ./public.crt:/root/.local/share/storj/gateway/minio/certs/public.crt
    #   - ./private.key:/root/.local/share/storj/gateway/minio/certs/private.key
    environment:
      - MINIO_BROWSER=off
      - MINIO_NOAUTH_ENABLED=enable
      - MINIO_NOAUTH_AUTH_URL=http://auth:8000
      - MINIO_NOAUTH_AUTH_TOKEN=staging
    ports:
      - "7777:7777"
    command:
      - run
    networks:
      gateway-mt: {}
  auth:
    image: storjlabs/authservice:dev
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1.5'
          memory: 1024M
        reservations:
          memory: 512M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    volumes:
      # - ./public.crt
      # - ./private.key
      - ./auth-db/:/app/db/
    ports:
      # remap auth port because many common docker services try to bind to 8000
      - "9000:8000"
    command:
      - run
      # this list can be updated from https://tardigrade.io/trusted-satellites
      - --allowed-satellites=12EayRS2V1kEsWESU9QMRseFhdxYxKicsiFmxrsLZHeLUtdps3S@us-central-1.tardigrade.io:7777,12L9ZFwhzVpuEKMUNUqkaTLGzwY9G24tbiigLiXpmZWKwmcNDDs@europe-west-1.tardigrade.io:7777,121RTSDpyNZVcEU84Ticf2L1ntiuUimbWgfATz21tuvgk3vzoA6@asia-east-1.tardigrade.io:7777,1wFTAgs9DP5RSnCqKV1eLf6N9wtk4EAtmN5DpSxcs8EjT69tGE@saltlake.tardigrade.io:7777,12rfG3sh9NCWiX3ivPjq2HtdLmbqCrvHVEzJubnzFzosMuawymB@europe-north-1.tardigrade.io:7777
      - --auth-token=staging
      - --public-url=http://localhost:9000
      - --endpoint=http://localhost:7777
      # - --cert-file=/app/public.crt
      # - --key-file=/app/private.key
    networks:
      gateway-mt: {}
networks:
  gateway-mt:
